

<div id="online-service">
  <ul class="online-serivce-list">
    <li class="first">&nbsp;</li>
    <li><img src="<?php print $this->getSkinUrl();?>/images/ww.png"/>客服一</li>
    <li><img src="<?php print $this->getSkinUrl();?>/images/ww.png"/>客服二</li>
    <li><img src="<?php print $this->getSkinUrl();?>/images/ww.png"/>客服三</li>
    <li><img src="<?php print $this->getSkinUrl();?>/images/ww.png"/>客服四</li>
    <li><img src="<?php print $this->getSkinUrl();?>/images/ww.png"/>客服五</li>
    <li class="last">&nbsp;</li>
  </ul>
</div>

